### ISSUE TITLE
Show the current status of an user

### ISSUE THREAD

**Issue by ThaHobbyist** [ThaHobbyist/HChat#4]
Add a feature such that while chatting with a user, you can see the current status of the user(online/offline/typing)

**Comment by DevilzzNikhil** [comment]
@ThaHobbyist  i can work on this would it be accept by hacktober

**Comment by DevilzzNikhil** [comment]
@ThaHobbyist  as many repo which i contribute were excluded

**Comment by ThaHobbyist** [comment]
Yes this will be included. All the tags that are needed are in place
